IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
DEFAULT_ANS_TOKEN = "<has_answer>"
DEFAULT_TODO_TOKEN = "<to_do>"
DEFAULT_SILENT_TOKEN = "<keep_silent>"
