"""Token roles and scoring constants used by the Decision model."""

QUERY_TOKEN = 1
MEMORY_TOKEN = 100
GLOBAL_MEMORY_TOKEN = 150
TIME_TOKEN = 200

SIMILARITY_TEMPERATURE = 0.1
LOSS_EPSILON = 1e-4
ENTROPY_REGULARIZATION_WEIGHT = 0.01

DEFAULT_SELECTED_CLIPS = 4
MAX_SELECTED_CLIPS = 28
DYNAMIC_SELECTION_THRESHOLD = 0.2
